=== Bizaarkq/xml-guia32-TPI115/Ejercicios/dtd_externa/ejercicio-ii-1b.dtd
<!ELEMENT fichero (titulo, ficha+)>
  <!ELEMENT titulo (#PCDATA)>
	<!ELEMENT ficha (nombre, apellido+, telefono, direccion*, dui?)>
  <!ATTLIST ficha
    tipo (empleado | gerente) "empleado">

	<!ELEMENT nombre (#PCDATA)>
	<!ATTLIST nombre
	  sexo (masculino|femenino) #REQUIRED
	  edad  CDATA  #IMPLIED>

	<!ELEMENT apellido (#PCDATA)>
  <!ATTLIST apellido
    tipoApe (primero | segundo | tercero) #REQUIRED>

	<!ELEMENT telefono (#PCDATA)>
  <!ATTLIST telefono
    tipo (fijo | celular) #REQUIRED>

	<!ELEMENT direccion (#PCDATA)>
	<!ELEMENT dui (#PCDATA)>

=== Bizaarkq/xml-guia32-TPI115/Ejercicios/dtd_externa/ejercicio-ii-1b-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ejercicio-ii-1b-dtd.xml  Grupo 13 -->
<?xml-stylesheet type="text/css" href="estilo-ii-1b.css"?>
<!DOCTYPE fichero SYSTEM "ejercicio-ii-1b.dtd">
<fichero>
  <titulo>Fichero</titulo>
  <ficha tipo="gerente">
    <nombre sexo="femenino">Angelina</nombre>
    <apellido tipoApe="primero">Fernandez</apellido>
    <telefono tipo="fijo">22577777</telefono>
    <direccion>c/Ulises, 36</direccion>
    <direccion>c/Tobias, 36</direccion>
    <dui>12345678-9</dui>
  </ficha>

<ficha>
    <nombre sexo="masculino">Andres</nombre>
    <apellido tipoApe="segundo">Henriquez</apellido>
    <telefono tipo="fijo">22577777</telefono>
    <direccion>c/Ulises, 36</direccion>
    <direccion>c/Tobias, 36</direccion>
    <dui>12345678-9</dui>
  </ficha>
</fichero>
