=== Bizaarkq/xml-guia32-TPI115/Ejercicios/dtd_externa/ejercicio10IV.dtd
<!ELEMENT curriculum (titulo, perfil, perfil,  elementos, a) >
  <!ELEMENT perfil (bloq? | bloque) >
  <!ELEMENT bloq (foto , nombre , apellido) >
  <!ELEMENT elementos (formacion , experiencia) >
  <!ELEMENT formacion (bloque*) >
  <!ELEMENT experiencia (bloque*) >
  <!ELEMENT bloque (subtitulo?, datos*) >
  <!ELEMENT titulo (#PCDATA) >
  <!ELEMENT foto EMPTY >
  <!ELEMENT nombre (#PCDATA) >
  <!ELEMENT apellido (#PCDATA) >
  <!ELEMENT subtitulo (#PCDATA) >
  <!ELEMENT a (#PCDATA) >
  <!ATTLIST subtitulo name CDATA #REQUIRED >
  <!ELEMENT datos (#PCDATA) >
  <!ATTLIST datos name CDATA #REQUIRED >
  <!ATTLIST foto src CDATA #IMPLIED xmlns CDATA #IMPLIED>
  <!ATTLIST a href CDATA #IMPLIED xmlns CDATA #IMPLIED target (_blank|_self|marco) "_blank">

=== Bizaarkq/xml-guia32-TPI115/Ejercicios/dtd_externa/ejercicio10IV.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="/Ejercicios/dtd_externa/ejercicio10IV.css"?>
<!DOCTYPE curriculum SYSTEM "ejercicio10IV.dtd">
<curriculum>
  <titulo>Curriculum Vitae</titulo>
  <perfil>
    <bloq>
      <foto xmlns="http://www.w3.org/1999/xhtml" src="http://davidinspections.com/wp-content/uploads/2017/02/avatar-hombre.jpg"/>
      <nombre>Joaquin Eleazar</nombre>
      <apellido>Aguilar Montero</apellido>
    </bloq>
  </perfil>
  <perfil>
    <bloque>
      <subtitulo name="perfil">Perfil</subtitulo>
      <datos name="Edad">30 años</datos>
      <datos name="Telefono">7000-2020</datos>
      <datos name="Direccion">San salvador, La colonia</datos>
      <datos name="Correo Electronico">curriculumtpi@mail.com</datos>
    </bloque>
  </perfil>
  <elementos>
    <formacion>
      <bloque>
        <subtitulo name="formacion">Formación</subtitulo>
        <datos name="Tiempo">4 años</datos>
        <datos name="Lugar">Colegio Nuevo San Salvador</datos>
        <datos name="Estudio realizado">Educación Básica</datos>
      </bloque>
      <bloque>
        <datos name="Tiempo">4 años</datos>
        <datos name="Lugar">Instituto Nacional Aprendiendo Todos</datos>
        <datos name="Estudio realizado">Bachillerato General</datos>
      </bloque>
    </formacion>
    <experiencia>
      <bloque>
        <subtitulo name="Experiencia">Experiencia</subtitulo>
        <datos name="Tiempo">4 años</datos>
        <datos name="Lugar">Empresa Credemax</datos>
        <datos name="Cargo">Programador</datos>
      </bloque>
    </experiencia>
  </elementos>
  <a xmlns="http://www.w3.org/1999/xhtml" href="../../index.html" target="marco">Regresar</a>
</curriculum>
