<?xml version="1.0" encoding="UTF-8"?>
<!-- ejercicio-ii-1a-dtd.xml  Grupo 13 -->

<!DOCTYPE fichero [
  <!ELEMENT fichero (titulo, ficha+)>
  <!ELEMENT titulo (#PCDATA)>
	<!ELEMENT ficha (nombre, apellido, telefono, direccion*, dui?)>
	<!ELEMENT nombre (#PCDATA)>
	<!ATTLIST nombre
	  sexo (masculino|femenino) #REQUIRED
	  edad  CDATA  #IMPLIED>

	<!ELEMENT apellido (#PCDATA)>
	<!ELEMENT telefono (#PCDATA)>
  <!ATTLIST telefono
    tipo (fijo | celular) #REQUIRED>

	<!ELEMENT direccion (#PCDATA)>
	<!ELEMENT dui (#PCDATA)>
]>
<fichero>
  <titulo>Fichero</titulo>
  <ficha>
    <nombre sexo="femenino">Angelina</nombre>
    <apellido>Fernandez</apellido>
    <telefono tipo="fijo">22577777</telefono>
    <direccion>c/Ulises, 36</direccion>
    <direccion>c/Tobias, 36</direccion>
    <dui>12345678-9</dui>
  </ficha>
</fichero>
